### ISSUE TITLE
This line is incorrect

### ISSUE THREAD

**Issue by devSahinur** [Mahadi92/code-rubric#1]
https://github.com/Mahadi92/code-rubric/blob/769e19fe6ffd56ca47a5555e25cb86847515c8a3/src/components/Home/Home.js#L24

This line is wrong for you "`React Router`" . it's "`react router dom`" Please change it bro #

**Comment by devSahinur** [comment]
> https://github.com/Mahadi92/code-rubric/blob/769e19fe6ffd56ca47a5555e25cb86847515c8a3/src/components/Home/Home.js#L24
> 
> This line is wrong for you "`React Router`" . it's "`react router dom`" Please change it bro

**Comment by mahadih-gg** [comment]
Thank you so much, brother.

**Comment by devSahinur** [comment]
> Thank you so much, brother.

welcome
